### ISSUE TITLE
init_notebook return AttributeError

### ISSUE THREAD

**Issue by makakin** [microsoft/msticpy#195]
**Describe the bug**
Showed error message: AttributeError: 'list' object has no attribute 'items', when run  init_notebook(namespace=globals());

**To Reproduce**
Successfully installed msticpy-1.3.1
❯ python
Python 3.9.6 (default, Jun 29 2021, 05:25:02)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from msticpy.nbtools.nbinit import init_notebook
>>> init_notebook(namespace=globals());

**Desktop (please complete the following information):**
 - OS: OSX 11.5.2

**Additional context**

<IPython.core.display.HTML object>
Processing imports....
Imported: pd (pandas), IPython.get_ipython, IPython.display.display, IPython.display.HTML, IPython.display.Markdown, widgets (ipywidgets), pathlib.Path, plt (matplotlib.pyplot), matplotlib.MatplotlibDeprecationWarning, np (numpy), msticpy, msticpy.data.QueryProvider, msticpy.nbtools.foliummap.FoliumMap, msticpy.common.utility.md, msticpy.common.utility.md_warn, msticpy.common.wsconfig.WorkspaceConfig, msticpy.datamodel.pivot.Pivot, msticpy.datamodel.entities
Checking configuration....
Setting notebook options....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/notebook/.venv/lib/python3.9/site-packages/msticpy/nbtools/nbinit.py", line 293, in init_notebook
    prov_dict = load_user_defaults()
  File "/Users/User/notebook/.venv/lib/python3.9/site-packages/msticpy/nbtools/user_config.py", line 74, in load_user_defaults
    prov_dict = _load_query_providers(user_defaults)
  File "/Users/User/notebook/.venv/lib/python3.9/site-packages/msticpy/nbtools/user_config.py", line 83, in _load_query_providers
    for prov_name, qry_prov_entry in user_defaults.get("QueryProviders").items():
AttributeError: 'list' object has no attribute 'items'

**Comment by makakin** [comment]
Sorry about that, it should be the msticpyconfig.yaml issue.
