### ISSUE TITLE
[Bug]: transform.process_tree_utils.get_process breaks when passing in a source index

### ISSUE THREAD

**Issue by ikiril01** [microsoft/msticpy#585]
**Describe the bug**
The `get_process` method takes either a Pandas Series or a string representing a source index. However, when passing in the source index string, it breaks with a KeyError, likely because the `.loc` call (https://github.com/microsoft/msticpy/blob/main/msticpy/transform/process_tree_utils.py#L108) is being used incorrectly.

**To Reproduce**

1. Run one of the methods that calls `get_process` such as `get_descendents` while passing in a source_index string. E.g., `get_descendents(process_tree, '20')`
2. See error

**Expected behavior**
The method runs successfully.

**Screenshots and/or Traceback**
Example stacktrace:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '20'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ikirillov/process_tree/logpack_to_process_tree.py", line 49, in <module>
    d = get_descendents(process_tree, pid_image_tuple[2])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/msticpy/transform/process_tree_utils.py", line 258, in get_descendents
    proc = get_process(procs, source)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/msticpy/transform/process_tree_utils.py", line 108, in get_process
    return procs.loc[source]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 4056, in xs
    loc = index.get_loc(key)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: '20'
```

**Environment (please complete the following information):**

- Python Version: 3.9
- OS: MacOS
- Python environment: Local
- MSTICPy Version: 2.2.0

**Additional information:**

I believe `loc` needs the name of the column to be passed in to function as intended and also requires a call to `squeeze` to return a Pandas Series. Something like: 

```
return procs.loc[procs['source_index'] == source].squeeze()
```

**Comment by ianhelle** [comment]
Hmm, yes I think this is "by design" but the design may not be that great.
When we build a process tree we create a DF with a index that uniquely identifies the process - it builds it from name + PID + timestamp I think.
So, the idea with these utilities is that you pass it one of these index values as the starting point, rather than the physical row number.
I'm open to ideas about how we could make this better though. E.g. we could extend these functions to take a source_index parameter rather than an index.

**Comment by ianhelle** [comment]
Actually I think you can use `get_process_key` to do what you want.
```python
get_descendents(process_tree, get_process_key(process_tree, 20))
```

**Comment by ianhelle** [comment]
if it is desperate that we directly support selecting by source_index I can add this logic to the functions. Please re-open the issue if that's a high priority for you.
